binop_separator = "Back"
brace_style = "PreferSameLine"
comment_width = 100
edition = "2024"
enum_discrim_align_threshold = 26
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_indent = "Visual"
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 26
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Never"
unstable_features = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
